# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: registration.proto for package 'registration'

module Registration
  module Codebreaker
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'registration.Codebreaker'

      rpc :Registration, ::Registration::Request, ::Registration::Reply


      def registration(request_args, _unused_call)
        # binding.pry
        Registration::Reply.new(message: RegistrationService.call(request_args))
      end
    end
  end
end
