# Generated by the protocol buffer compiler.
# Source: registration.proto for package 'registration'

module Registration
  module Codebreaker
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'registration.Codebreaker'

      rpc :Registration, ::Registration::Request, ::Registration::Reply


      def registration(request_args, _unused_call)
        status, msg = ::RegistrationService.call(request_args)

        raise GRPC::BadStatus.new(GRPC::Core::StatusCodes::INVALID_ARGUMENT, msg) if status == :failure

        Registration::Reply.new(message: )
      end
    end
  end
end
