# Generated by the protocol buffer compiler.
# Source: statistic.proto for package 'statistic'

module Statistic
  module Codebreaker
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'statistic.Codebreaker'

      rpc :Statistic, ::Statistic::Request, ::Statistic::Reply

      def statistic(_request_args, _unused_call)
        Statistic::Reply.new(statistic: ::StatisticService.call)
      end
    end
  end
end
